# Generated by Django 4.0.2 on 2022-03-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'created', 'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='no',
            field=models.SlugField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='no',
            field=models.SlugField(blank=True, max_length=10, unique=True),
        ),
    ]
